RSV:=(CLOSE-LLV(LOW,P1))/(HHV(HIGH,P1)-LLV(LOW,P1))*100;
K:SMA(RSV,P2,1),COLORFF8D1E;
D:SMA(K,P3,1),COLOR0CAEE6;
J:3*K-2*D,COLORE970DC;

HUNDRED:=100;
ZERO:=0;

JCROSSZERO:=IF(CROSS(J,ZERO),1,0);
JCROSSHUNDRED:=IF(CROSS(J,HUNDRED),1,0);
DRAWICON(JCROSSZERO,J,38);
DRAWICON(JCROSSHUNDRED,J,38);

ZEROCROSSJ:=IF(CROSS(ZERO,J),1,0);
HUNDREDCROSSJ:=IF(CROSS(HUNDRED,J),1,0);
DRAWICON(ZEROCROSSJ,J,39);
DRAWICON(HUNDREDCROSSJ,J,39);

{ZIGPOINT:=IF(J>100,ZIG(J,0.01),0);}
{DRAWNUMBER(J>100 AND REF(ZIGPOINT,2)<REF(ZIGPOINT,1) AND REF(ZIGPOINT,1)>ZIGPOINT,50,REF(ZIGPOINT,1));}
{TOP:=}
